### ISSUE TITLE
Possible changes to increase speed

### ISSUE THREAD

**Issue by zappybiby** [ajchili/bglf#1]
Currently, I believe that having the script drag from the first two items is the fastest. However, I have not done rigorous testing. 

I know that our current method is faster than manually dragging and both manually/automatically right clicking.

Possible changes:

1. Make `MouseClickDrag` speed a little slower to compensate for typical server lag
2. Try other combinations of dragging from x amount of items when the script is activated
3. Possibly make it double drag (Having two identical MouseClickDrag functions) to ensure the item is actually moved.

**Comment by ajchili** [comment]
Might be best to look into options 1 and 3. My main issue when trying to get this to work 'properly' was server lag.

**Comment by zappybiby** [comment]
Tested option 3 - it was notably worse and nowhere near as fast. Plus it usually skipped a few items.

**Comment by ajchili** [comment]
This seems to have been fixed. The double drag and iteration changer feature seem to have worked. If not, the issue can be reopened.
