### ISSUE TITLE
Ensuring compatability with common screen resolutions

### ISSUE THREAD

**Issue by zappybiby** [ajchili/bglf#2]
Need to test different monitor resolutions to ensure our current linear function of `62.5x + 99.5` is accurate for scaling.

I started comparisons on https://github.com/ajchili/bglf/blob/465258e2c3f0b2b5290a984f694246924b44156a/main.ahk#L34
where we can place the different heights for each item for each resolution. Use AU3_Spy.exe to determine their location. Try to get coords as close to the center of the box as possible.

**Comment by ajchili** [comment]
The best way to do this would be to find the difference between 1080p and 1440p. Then make a quick algorithm that will calculate for any 16:9 resolution.

**Comment by zappybiby** [comment]
1440p is 1.3x bigger in width and height when compared to 1080p

To confirm this, https://github.com/ajchili/bglf/blob/master/main.ahk#L11 shows that 1080p has the center of the box of the first item at 160px. 160px * 1.3 = 208px, which is relatively close to the 230px we initially found.

So estimates for the width coords for 1440p are 208, 292.5, 377, 461.5, 546
Which gives the function of `84.5x+123.5`

1080p increases by 65px each item, while 1440p increases by ~84.5px for each item.

**Comment by zappybiby** [comment]
720p is 2/3x smaller than 1080p:
So estimated coords are: 107, 150, 193, 237, 280
Which gives the function `43.3 x + 63.5`

720p increases by ~45px, 1080p increases by 65px, 1440p increases by ~85px

**Comment by zappybiby** [comment]
In the case a maniac decides to run this game at 4k: 

4k is 2x bigger than 1080p
So estimated coords are: 320, 450, 580, 710, 840
Which gives the function `130x+190`

720p increases by ~45px, 1080p increases by 65px, 1440p increases by ~85px, 4k increases by 130px

**Comment by zappybiby** [comment]
To make functions consistent:
```
720p:  45x + 61
1080p: 65x + 95
1440p: 85x + 123
4k:   130x + 190
```

**Comment by ajchili** [comment]
Now we just have to work on a scaling function that will determine the x step and additional pixel calculation.

**Comment by ajchili** [comment]
Check [this link](https://github.com/ajchili/bglf/commit/8252c2c89220fa614cdba0494d1bb48264bcdc66) and look at the function. It should semi-work, but I have not tested it yet.

**Comment by zappybiby** [comment]
I changed formula to `65x + 95`, it works great on 1080p

**Comment by zappybiby** [comment]
Just to make sure this works:

Since 4k is just 2x bigger than 1080p
then our formulas would be 
```
sy := (65 * (Height / 1080.0)) + (95 * (Height / 1080.0))
and
sy2 := (65 * (2 * (Height / 1080.0)) + ((95 * (Height / 1080.0))
```
For 4k: `(65 * (2160 / 1080.0)) + (95 * (2160 / 1080.0)) = 320` 
which gives the estimated coords we got for the first item box.

For 720p: `(65 * (720/ 1080.0)) + (95 * (720/ 1080.0))= ~106.6`
which is close to our estimated coords of 107 for first item

**Comment by ajchili** [comment]
This seems to have been fixed, at least for 16:9 resolutions. Future revisions to the script may occur to allow for different aspect ratios.
